version: "3"

services:
  app-1: &app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: app-1
    networks:
      - rede
  
  app-2:
    <<: *app
    container_name: app-2

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rede
  
  nginx:
    image: nginx:latest
    volumes:
      - ./extras/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:80"
    networks:
      - rede

networks:
  rede:
    driver: bridge
