version: "3"

services:
  #app-1: &app
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  restart: always
  #  container_name: app-1
  #  ports:
  #    - "8082:8082"
  #
  #app-2:
  #  <<: *app
  #  container_name: app-2
  #  ports:
  #    - "8083:8082"

  database:
    image: redis:latest
    container_name: redis-db
    restart: always
    command: redis-server --requirepass pass
    ports:
      - "6379:6379"
