version: "3"

services:
  #app-1: &app
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  restart: always
  #  container_name: app-1
  #  ports:
  #    - "8082:8082"
  #
  #app-2:
  #  <<: *app
  #  container_name: app-2
  #  ports:
  #    - "8083:8082"

  cache:
    image: redis:latest
    restart: always
    command: redis-server --requirepass pass
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
